app.cors.allowed-origins=https://uniquehan.com,https://www.uniquehan.com,https://*.vercel.app

spring.jpa.hibernate.ddl-auto=validate
# validate, create, update

spring.sql.init.mode=never
# always, never